Traceback (most recent call last):
  File "/Users/kyamauch/opt/miniconda3/envs/napari-tutorial/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/kyamauch/opt/miniconda3/envs/napari-tutorial/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kyamauch/opt/miniconda3/envs/napari-tutorial/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kyamauch/opt/miniconda3/envs/napari-tutorial/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kyamauch/opt/miniconda3/envs/napari-tutorial/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kyamauch/opt/miniconda3/envs/napari-tutorial/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/kyamauch/opt/miniconda3/envs/napari-tutorial/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/kyamauch/opt/miniconda3/envs/napari-tutorial/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
viewer = napari.view_image(
    nuclei,
    colormap='blue',
    contrast_limits=(0, 0.4)
);

# choose the z slice where nuclei are in focus
viewer.dims.current_step = (30, 0, 0)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/hd/p540nk9s5cl9tcwdzjg2flnh0000gr/T/ipykernel_85433/3102700907.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m viewer = napari.view_image(
[0m[1;32m      2[0m     [0mnuclei[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mcolormap[0m[0;34m=[0m[0;34m'blue'[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mcontrast_limits[0m[0;34m=[0m[0;34m([0m[0;36m0[0m[0;34m,[0m [0;36m0.4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m );

[0;31mNameError[0m: name 'napari' is not defined
NameError: name 'napari' is not defined

